Added YIO and HEIDI datasets, changed tests and references to "q" former namings
globalgov/manyenviron pull request #49
Opened 2022-02-01 16:11 UTC by EstherPeev

# Description

These patch changes includes the change of the last references to qData, qID_ref into manydata and many_ID, modification of the tests as well as the addition of YIO and HEIDI datasets.

## Package

* Fixed #46 by simplifying tests for texts database
* Fixed #48 by moving to bootstrap 5 in pkgdown file
* Closed #43 by using treaty texts to create `code_lineage`

## Data

**Added datasets**
* Closed #13 by web scraping YIO pages
* Added HEIDI dataset

**Added columns in datasets**
* Closed #42 by adding Lineage column in datasets in agreements database
* Closed #44 by adding membership column 

# Checklist:

- [X] PR form
  - [X] I have given this pull request an informative title
  - [X] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [X] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [X] Package builds on my OS without issues
- [X] PR checks all pass for latest commit
  - [X] Package builds on Mac
  - [X] Package builds on Windows
  - [X] Package builds on Linux
  - [X] CodeCov check: Package improves or maintains good test coverage
  - [X] CodeFactor check: Package improves or maintains good style
- [X] Documentation
  - [X] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [X] Any longer functions are commented inline so that it is easier to debug in the future
  - [X] PR description above and the NEWS.md file are aligned
  - [X] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-02-01 20:23 UTC, jhollway requested changes
Thanks @EstherPeev, looks good. A few requests, and then there might be some more for the next version.

2022-02-01 20:23 UTC, jhollway commented on data-raw/organizations/YIO/prepare-YIO.R
> +urls <- paste0("https://uia.org/ybio?page=", 1:3004)
This is hard-coded for a certain number of entries. If this could change, can we add a step that lookups the necessary length(s)?

2022-02-03 08:57 UTC, henriquesposito reviewed
Great job Esther! I have added some minor review comments, once you address those we should be good to go on my side! As always, please try to make sure you check  if the website is building properly locally and run a lintr check for coding best practices before merging.

2022-02-03 08:57 UTC, henriquesposito commented on R/manyenviron-agreements.R
> +#' lapply(agreements, skimr::skim_without_charts)
Should you not add the skimr package to the imports section in description file for this code chunk work properly?

2022-02-03 08:57 UTC, henriquesposito commented on R/manyenviron-agreements.R
> +#' 12 variables: manyID, Title, Beg, End, L, D, J, Signature, Force,
I like manyID without the "_" better as well, great job! Could you please open a new issue for updating the variable names to be consistency with these in all of our packages? Thank you!

2022-02-03 08:57 UTC, henriquesposito commented on R/manyenviron-memberships.R
> +#' lapply(memberships, skimr::skim_without_charts)
skimr package needs to be imported?

2022-02-03 08:57 UTC, henriquesposito commented on R/manyenviron-organizations.R
> +#' 4 variables: Title, Abbreviation, Beg, Country.}
No @details code chunk here?

2022-02-03 08:57 UTC, henriquesposito commented on R/manyenviron-texts.R
> +#' lapply(texts, skimr::skim_without_charts)
skimr package needs be imported?

2022-02-03 10:50 UTC, henriquesposito approved these changes
Great job, thank you Esther!

2022-02-03 10:56 UTC, merged