Added and updated datasets, connected to Shinyapp
globalgov/manyenviron pull request #56
Opened 2022-03-10 15:42 UTC by jaeltan

# Description
Patch changes to the package including the addition of new data and renaming of existing variables in the agreements database so that names do not start with the same letters.

## Package
* Closed #53 by adding Shinyapp folders, dashboard vignette and connecting to a Shinyapp account.

## Data
* Closed #15 by adding `International Regimes Database` to the `regimes` database.
* Fixed #55 by renaming variables in databases to avoid ambiguity
  * Renamed variables "L", "D", and "J" in the agreements database "DocType", "AgreementType", and "GeogArea" respectively
  * Renamed variables "L" and "signatureC" in memberships database "DocType" and "SignatureCountry" respectively

# Checklist:

- [X] PR form
  - [X] I have given this pull request an informative title
  - [X] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [X] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [X] Package builds on my OS without issues
- [x] PR checks all pass for latest commit
  - [x] Package builds on Mac
  - [x] Package builds on Windows
  - [x] Package builds on Linux
  - [x] CodeFactor check: Package improves or maintains good style
- [X] Documentation
  - [X] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [X] Any longer functions are commented inline so that it is easier to debug in the future
  - [X] PR description above and the NEWS.md file are aligned
  - [X] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-03-11 09:26 UTC, henriquesposito requested changes
@jaeltan Thank you so much for addressing this issue so promptly, I appreciate it! 

I have left some comments and requested a few changes, please let me know if you have any questions about them.

On more thing, could you please double check that we not have the same variable issues in the other databases beyond agreements? If so, could you please rename variable there as well. Please also double check that consolidate() runs on the databases without issues. Thank you very much and please let me know if you need any help!

2022-03-11 09:26 UTC, henriquesposito commented on NEWS.md
> +* Fixed #55 by renaming 'Lineage' variable to 'R' in agreements database to avoid clashing with the variable 'L'.
Could you please actually rename the "L" variable and all the other variables that have a single letter? This way we avoid having the same issues in the future. I would suggest leaving the "Lineage" variable name but renaming the other single letter variables with a more informative word name (i.e. what does the "L", and "J", and "D", and so on stand for).

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/agreements/CIESIN/prepare-CIESIN.R
> +CIESIN$R <- manypkgs::code_lineage(CIESIN$Title)
Please avoid single letter names.

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/agreements/ECOLEX/prepare-ECOLEX.R
> +ECOLEX$R <- manypkgs::code_lineage(ECOLEX$Title)
Please avoid single letter names.

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> +GNEVAR$R <- manypkgs::code_lineage(GNEVAR$Title)
Please avoid single letter names.

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/agreements/HEIDI/prepare-HEIDI.R
> +HEIDI$R <- manypkgs::code_lineage(HEIDI$Title)
Please avoid single letter names.

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/agreements/IEADB/prepare-IEADB.R
> +IEADB$R <- manypkgs::code_lineage(IEADB$Title)
Please avoid single letter names.

2022-03-11 09:26 UTC, henriquesposito commented on data-raw/regimes/IRD/prepare-IRD.R
> +  dplyr::select(Regime, RegimeComponent, Beg, Wat, Wat2, End, RegimeElement)
Are Wat and Wat2 the same or different? The same is true for the variables Regime and RegimeComponent. If different please assign a different name prefix to avoid confusion. Could you please also double check and change when this happens for all other datasets in databases?

2022-03-11 09:26 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
> +      - text: Lineage Chain of Environmental Treaties
Maybe just "Lineage of Environmental Treaties"

2022-03-11 09:26 UTC, henriquesposito commented on vignettes/lineage_dashboard.Rmd
> +title: "Lineage Chain of Environmental Treaties"
Lineage of Environmental Treaties

2022-03-11 09:26 UTC, henriquesposito commented on vignettes/membership_dashboard.Rmd
> +title: "Types of Environmental Treaties"
Does this vignette runs/work fine? If so, could you please can add an article for it in the pkgdown website so that users can begin to play around with it? Otherwise, if it does not work fine, you can just leave here without adding it. I still have to work on all these shinyapps dashboards to make them cooler/fancier.

2022-03-11 09:26 UTC, henriquesposito commented on shinyapp/memberships/app.R
> +
Does this work/run fine? Could you please double check and let me know. You are also welcome to make changes/re-work if it does not or if you want to improve it a bit.

2022-03-11 11:34 UTC, jaeltan commented on data-raw/regimes/IRD/prepare-IRD.R
> +  dplyr::select(Regime, RegimeComponent, Beg, Wat, Wat2, End, RegimeElement)
For the IRD, Wat and Wat2 both refer to a period of fundamental change in the regime, but for some regimes there may be more than one such period, hence the 2. I think we can keep them as is. I also think it is better to keep the prefix 'regime' in front of component in RegimeComponent because it is clearer that in this terminology that the components are (sub)parts of the regimes, as the authors of the IRD intended to express. Instead of changing the names I could add comments to the script so that it is clearer what the variable names refer to? @henriquesposito

2022-03-11 11:42 UTC, henriquesposito commented on data-raw/regimes/IRD/prepare-IRD.R
> +  dplyr::select(Regime, RegimeComponent, Beg, Wat, Wat2, End, RegimeElement)
@jaeltan Thank you for the prompt reply! I understand your point and as long as consolidate() works on the database/datasets it should be fine (though I have a suspicion it will not). However, be aware that if consolidate() works in the database it likely means it is consolidating these two variables as one (i.e. Wat and Wat2 will be understood as the same variable for consolidate()). I will also try to modify consolidate() to be "smarter" in relation to these ambiguities in the future I think.

2022-03-11 11:46 UTC, jaeltan commented on vignettes/membership_dashboard.Rmd
> +title: "Types of Environmental Treaties"
I tried knitting this and the lineage_dashboard, only the title appears and sometimes a few links at the side, but no actual content. @henriquesposito

2022-03-11 11:51 UTC, jaeltan commented on data-raw/regimes/IRD/prepare-IRD.R
> +  dplyr::select(Regime, RegimeComponent, Beg, Wat, Wat2, End, RegimeElement)
Ok, at the moment there is only the IRD dataset in the database so there isn't much point running consolidate() on it now. But when we add other datasets I will think of a way to better name the variables across the database!

2022-03-11 11:59 UTC, henriquesposito commented on vignettes/membership_dashboard.Rmd
> +title: "Types of Environmental Treaties"
Ok, thank @jaeltan ! I will look into it, but I think we can leave the memberships dashboard aside for the time being since I do not think it is ready in any case.

2022-03-11 12:01 UTC, henriquesposito commented on DESCRIPTION
> +Date: 2022-03-11
@jaeltan Please also remember to add your name here since you are now a contributor here as well!

2022-03-11 12:10 UTC, jaeltan commented on shinyapp/memberships/app.R
> +
The app file works fine!

2022-03-11 13:15 UTC, henriquesposito reviewed
Thank you @jaeltan , really great work!

Just two comments. First, when I run the cmd Checks locally I get several notes, they should not be an issue but could you try and see what they are about and if there is anything we can do about these?

Second, I also get several warnings related to `{skimr}` not working with "messydt" class... @BBieri can we add simple a template on manyenviron for the data documentation that works with "messydt" class? Thank you!

2022-03-11 13:15 UTC, henriquesposito commented on NEWS.md
> +* Fixed #55 by renaming 'Lineage' variable to 'R' in agreements database to avoid clashing with the variable 'L'.
You renamed other variables as well, could you please be more specific here? 

* Fixed #55 by renaming variables in databases to avoid ambiguity
  * Renamed variables "L", "D", and "J" in the agreements database "DocType", "AgreementType", and "GeogArea" respectively
  * renamed variables "L" and "signatureC" in memberships database "DocType" and "SignatureCountry" respectively

2022-03-14 21:43 UTC, jhollway approved these changes

2022-03-16 09:33 UTC, merged