Updates to workflow files
globalgov/manyenviron pull request #58
Opened 2022-07-19 12:57 UTC by jaeltan

# Description

## Package

* Fixes #(issue no.)
* Closes #(issue no.)

## Data

* Fixes #(issue no.)
* Closes #(issue no.)

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
  - [ ] CodeCov check: Package improves or maintains good test coverage
  - [ ] CodeFactor check: Package improves or maintains good style
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2022-07-26 10:04 UTC, henriquesposito requested changes
Thank you for all the great work @jaeltan ! I requested some minor changes, please let me know if you have any questions.

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/agreements/HEIDI/prepare-HEIDI.R
> +# in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/agreements/IEADB/prepare-IEADB.R
> +# in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/memberships/ECOLEX_MEM/prepare-ECOLEX.R
> +#in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/memberships/GNEVAR_MEM/prepare-GNEVAR.R
> +#in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/memberships/IEADB_MEM/prepare-IEADB.R
> +#in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/memberships/TFDD_MEM/prepare-TFDD.R
> -#in as much detail about the variables etc as possible.
line...

2022-07-26 10:04 UTC, henriquesposito commented on data-raw/organizations/MIA/prepare-MIA.R
> -#in as much detail about the variables etc as possible.
line...

2022-07-28 09:36 UTC, jaeltan commented on data-raw/agreements/GNEVAR/prepare-GNEVAR.R
> -#in as much detail about the variables etc as possible.
I ran lintr::lint_package() but I'm not seeing any of these?

2022-07-29 12:10 UTC, jaeltan commented on .Rbuildignore
> +^shinyapp$
I think it's already been included?

2022-07-31 14:55 UTC, jhollway commented on DESCRIPTION
> +    R (>= 3.5.0)
Does it need to Depend on manydata for everything to print and work correctly?

2022-07-31 14:55 UTC, jhollway commented on NEWS.md
> +* Added `accessionC` and `accessionP` variables for accession conditions and procedures respectively in `GNEVAR` dataset in `agreements` database.
Can you tell us a little more about these variables?

2022-08-02 08:40 UTC, henriquesposito requested changes
Thank you @jaeltan for the great job with this package! Just a few minor points to check/adress and then we should be good to go with the merge.

2022-08-02 08:40 UTC, henriquesposito commented on .github/workflows/pushrelease.yml
> +        run: mv ./macOS/*.tgz pkg_macOS.tgz
Just a detail, but could you please change the "pkg" throughout the file for  "manyenviron"? Thank you.

2022-08-02 08:40 UTC, henriquesposito commented on DESCRIPTION
> +    R (>= 3.5.0)
Great job @jaeltan in trimming the package imports and suggests here. You can move manydata to suggests if you would like. Could you also please add messydates to the suggested packages? Just because we rely on messydates for documenting databases.

2022-08-02 08:40 UTC, henriquesposito commented on vignettes/connect.Rmd
> +references <- manyenviron::references$ECOLEX_REF %>%
@jaeltan Could you please just double check if these vignettes build properly, if the website builds without any warnings, and if the shiny dashboards work ok? I still need to improve the dashboard but they should work... Thank you!

2022-08-02 10:49 UTC, jaeltan commented on vignettes/connect.Rmd
> +references <- manyenviron::references$ECOLEX_REF %>%
They work!

2022-08-03 08:50 UTC, jhollway approved these changes

2022-08-03 08:50 UTC, jhollway commented on DESCRIPTION
> +    manydata,
Can we make manydata a depends instead of a suggests for all manyverse/data packages?

2022-08-03 11:37 UTC, henriquesposito commented on DESCRIPTION
> +    manydata,
Yes we can. However, CMD tests return a "Note" when we do so (since the NAMESPACE file does not point to manydata). As long as we are fine with that we can add without issues. I added to the templates for new package in manypkgs and here already just in case.

2022-08-03 11:39 UTC, jhollway commented on DESCRIPTION
> +    manydata,
So why not add an `#' @imports manydata` line to one or more of the data object documentations?

2022-08-03 11:47 UTC, henriquesposito commented on DESCRIPTION
> +    manydata,
Yes, that would work! Or, perhaps, another solutions is to move the `mreport()` function from messydates to manydata and, therefore, we would rely on it for the documentation for all databases (as we currently have). @jaeltan and @jhollway what do you think?

2022-08-15 08:53 UTC, jaeltan commented on DESCRIPTION
> +    manydata,
We could move `mreport()` to `manydata` so that all the data reporting functions are listed together in `manydata`, but as @henriquesposito said this would add a `manydata` dependency in `messydates`. If ultimately all the many packages should have manydata dependency, we could move this would not be an issue and we could move the function over now @jhollway ?

2022-08-15 11:43 UTC, jhollway commented on DESCRIPTION
> +    manydata,
The ambition was to have messydates be as independent as possible so that it could conceivably serve non-manydata interests. We also need to avoid reciprocal package dependencies, as this then becomes particularly sensitive to anything breaking down.

2022-08-16 09:29 UTC, jaeltan commented on DESCRIPTION
> +    manydata,
Ok I added a `@imports manydata` line to the `texts` data documentation

2022-08-16 09:42 UTC, merged