Verified metadata and added raw TreatyTexts
globalgov/manyenviron pull request #71
Opened 2023-02-23 08:34 UTC by delmoralsu

# Description

Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url` for treaties in HUGGO_verified.csv, then merged into the original HUGGO dataset. Added treaties present in ECOLEX, IEADB, CIEISIN and HEIDI datasets that were not in the original HUGGO dataset, verifying their metadata. Added treaty texts of environmental agreements in the `HUGGO` dataset, and stored them in ".txt" files.

## Data

* Closed #67 by verifying `Beg` `End` `Signature` `Force` in HUGGO dataset.
* Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url` for 465 treaties in  `HUGGO_verified.csv `, then merged into the original HUGGO dataset.
* Added 196 treaties present in ECOLEX, IEADB, CIEISIN and HEIDI datasets that were not in the original HUGGO dataset to  `HUGGO_additional.csv `, then merged into the original HUGGO dataset. Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url`.
* Added 657 raw treaty texts and 70 formatted treaty texts, stored in ".txt" files.

# Checklist:

- [x] PR form
  - [x] I have given this pull request an informative title
  - [x] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [x] Package builds on my OS without issues
- [x] Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Any longer functions are commented inline so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-03-02 11:20 UTC, henriquesposito commented
Thank you for all the great work @delmoralsu and @jaeltan !

I see the issues with conflicts here and I am also not sure what is happening.

My suggestions: 

1. If the conflicts in the agreements.rda file are related to the exporting of the HUGGO dataset, what I suggest is only merging the changes to the HUGGO data raw files (csv and txt) to the develop branch and, then, overwriting the HUGGO file in agreements database using ´export_data()´ in the develop branch directly. That is, only merge changes to the raw datasets and refrain from merging changes in the database. 

2. Otherwise, if the above is not the case and you are sure the agreements.rda databases are the same in the develop and in this branch, you can simply copy the data folder and the respective documentation files in one or the other branch. If that still does not work, you can delete the folder and respective documentation in the develop branch before merging the branches. 

3. Lastly, there are two other "radical" alternatives. You can push all these changes directly to the develop branch or selectively merge only specific files from this branch into develop (see https://jasonrudolph.com/blog/2009/02/25/git-tip-how-to-merge-specific-files-from-another-branch/ and https://stackoverflow.com/questions/449541/how-can-i-selectively-merge-or-pick-changes-from-another-branch-in-git). 

I hope this helps, please let me know.

2023-03-06 12:51 UTC, jaeltan requested changes
Thank you for all the hard work and effort you have put into the package @delmoralsu ! I can see a lot has been done, great job with the merging and updating the files, I just have a few minor suggestions for you here then we should be ok to merge.

2023-03-06 12:51 UTC, jaeltan commented on NEWS.md
> +## Data
Thanks for updating the NEWs file! We only copy and paste the section under the subheadings, but here your PR description above is more detailed than that below the subheading. I think we can reorder some of this information and put more details under the subheading that is included in the NEWs file?

The News also needs to be under a new version number so that we know which release this description is for. # manyenviron 0.2.1 should be above 2022-10-11. The version number changes with every PR. I think you can change it to 0.3.0 here.

2023-03-06 12:51 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +# Add column for treaty text collection
do you mean to indicate if treaty text has been collected? can you use `dplyr::mutate()` to do this?

2023-03-06 12:51 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- dplyr::mutate(merged_df, Beg = as_messydate(Beg),
Can you check that all NAs are coded correctly and dataset is arranged by Beg as well?

2023-03-06 13:50 UTC, delmoralsu commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +# Add column for treaty text collection
Yes, this column should indicate if there is a corresponding txt file with the treaty text. I used `dplyr::mutate()` to add the column and set its name and content.

2023-03-06 13:57 UTC, delmoralsu commented on NEWS.md
> +## Data
Reordered the information in the Description and Subheading of the PR, and updated the NEWs file accordingly. Changed the version number to 0.30.

2023-03-06 13:58 UTC, delmoralsu commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- dplyr::mutate(merged_df, Beg = as_messydate(Beg),
Checked the NAs, and added a final line to arrange the dataset by `Beg` before exporting it.

2023-03-07 08:19 UTC, jaeltan requested changes
Thanks Diego, just a few more minor changes.

2023-03-07 08:19 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- arrange(HUGGO_new)
You can add this to the previous code section and remember to add `dplyr::arrange()`. Also you can directly assign this to HUGGO, so there would be no need to add the extra line HUGGO <- HUGGO_new later

2023-03-07 08:19 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
>               "BLR-EGY[QPT]_1998A", "BLR-SYR[SAI]_2003A", "BRA-CRI[CET]_2008P",
can you replace 37 in the for loop with `length(misstxt)`?

2023-03-07 08:19 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_back <- HUGGO_new
What is this HUGGO_back for?

2023-03-07 09:48 UTC, delmoralsu commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_back <- HUGGO_new
My bad, I removed these lines dealing with HUGGO_back. It was a way to test the removal of duplicates and to have a backup of HUGGO_new in case something did not work.

2023-03-07 09:52 UTC, jaeltan approved these changes

2023-03-07 09:52 UTC, merged