Develop
globalgov/manyenviron pull request #73
Opened 2023-03-07 09:54 UTC by jaeltan

# Description

Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url` for treaties in HUGGO_verified.csv, then merged into the original HUGGO dataset. Added treaties present in ECOLEX, IEADB, CIEISIN and HEIDI datasets that were not in the original HUGGO dataset, verifying their metadata. Added treaty texts of environmental agreements in the `HUGGO` dataset, and stored them in ".txt" files.

## Data

* Closed #67 by verifying `Beg` `End` `Signature` `Force` in HUGGO dataset.
* Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url` for 465 treaties in  `HUGGO_verified.csv `, then merged into the original HUGGO dataset.
* Added 196 treaties present in ECOLEX, IEADB, CIEISIN and HEIDI datasets that were not in the original HUGGO dataset to  `HUGGO_additional.csv `, then merged into the original HUGGO dataset. Verified `Title`, dates (`Beg`, `End`, `Signature`, Force) and `url`.
* Added 657 raw treaty texts and 70 formatted treaty texts, stored in ".txt" files.

# Checklist:

- [ ] PR form
  - [ ] I have given this pull request an informative title
  - [ ] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [ ] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [ ] Package builds on my OS without issues
- [ ] PR checks all pass for latest commit
  - [ ] Package builds on Mac
  - [ ] Package builds on Windows
  - [ ] Package builds on Linux
- [ ] Documentation
  - [ ] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [ ] Any longer functions are commented inline so that it is easier to debug in the future
  - [ ] PR description above and the NEWS.md file are aligned
  - [ ] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

2023-03-08 08:23 UTC, jaeltan commented on data-raw/agreements/HUGGO/HUGGO_verified.csv
>  JPN-USA[FSF]_1967N;Exchange Of Notes Constituting An Agreement Between The United States Of America And Japan Concerning Salmon Fisheries;1967-05-09;1970-12-11;1967-05-09;1967-05-09;A;B;L;GENG-0791;#
Can you change the csv files to separation by comma (,) instead of semicolon (;) and the '#N/D' to NA?

2023-03-08 08:25 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- HUGGO_new[-(which(str_detect(HUGGO_new$manyID, "[^[:ascii:]]"))), ]
Does this delete the row or just the non-ASCII character?

2023-03-08 08:50 UTC, henriquesposito commented
Great job @delmoralsu and @jaeltan !

For the issue with non-ACSII characters, I would suggest translating these to latin (instead of removing them as we are currently attempting). One way to do so is using the ´stringi::stri_trans_general(str, "latin-ascii")´ function.

If there are many non-ACSII characters throughout the files in the R package, you can use the ´tools::showNonASCII()´and ´tools::showNonASCIIfile()´ functions to help identify where these are located.

Please let me know if you need help or have any questions about this. Thank you.

2023-03-08 11:16 UTC, delmoralsu commented
> 

I'm on it. In the case of texts in Russian or other languages that do not use the latin alphabet, should I translate them into English?

2023-03-08 12:03 UTC, henriquesposito commented
Thank you for the question @delmoralsu ! 

In theory, you could translate non-ASCII characters in other alphabets as long as you define it within the ´stringi::stri_trans_general()´ function (see ´stringi::stri_trans_list()´ for more options). 

However, I think we should go ahead and translate texts to english now and either keep the original texts as an additional variable or create an additional variable to signal that we translated the text from a certain source.

@jaeltan and @jhollway what do you think? Thank you!

2023-03-08 14:07 UTC, delmoralsu commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- HUGGO_new[-(which(str_detect(HUGGO_new$manyID, "[^[:ascii:]]"))), ]
It deletes the whole row. I verified the data in that row and it is in HUGGO_verified, but because the `manyID` has a non-ASCII character (CZE-HUN[R¸S]_1968A), I changed it to the corresponding `treatyID` (CZE-HUN[RGS]_1968A).

2023-03-09 08:07 UTC, jaeltan commented
Thank you @delmoralsu @henriquesposito for the work on the texts, I agree that we should translate the texts to English now to remove the non-ASCII characters and since we would probably need to do so in the future. I think for the sake of transparency it makes sense to create a variable to track which texts were translated from another language or to record the original language of the text.

2023-03-09 08:27 UTC, jaeltan commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- HUGGO_new[-(which(str_detect(HUGGO_new$manyID, "[^[:ascii:]]"))), ]
I don't see this documented anywhere in the preparation script. If you made the changes to the manyIDs in the HUGGO_verified.csv file to remove non-ASCII characters, is it correct that if other users are replicating this rows with ASCII characters in the manyID would not appear when running the script?

2023-03-09 09:23 UTC, delmoralsu commented on data-raw/agreements/HUGGO/prepare-HUGGO.R
> +HUGGO_new <- HUGGO_new[-(which(str_detect(HUGGO_new$manyID, "[^[:ascii:]]"))), ]
I see the issue. I'll revert that change from the csv and handle it within the preparation script.

2023-03-16 09:46 UTC, henriquesposito commented
@delmoralsu thank you for all the hard work! 

I am looking through the issues with `{sf}` installation for Linux and it appears that it is an issue for latest versions of the OS, that is why it fails. It apparently has been fixed in the development version of the package, but these changes have not been released (e.g. see https://github.com/r-spatial/sf/issues/2121). 

I will just comment out the Linux checks, for now, and we can uncomment these once this PR is merged for next time.

2023-03-16 10:26 UTC, delmoralsu commented
Thanks @henriquesposito! Is it intended that the checks try to install `{sf}`? Previous Ubuntu checks that were succesful did not install it. 

In any case, browsing through the Ubuntu check output, I noticed that in the latest one it tries (and fails) to load cache for Ubuntu 20.04.5 LTS-R version 4.2.3 (2023-03-15) to install/update packages, whereas in previous checks the R version was 4.2.2. I don't know if this is relevant, although it might be in terms of bandwith because it then proceeds to download 185 packages.

2023-03-16 10:56 UTC, henriquesposito requested changes
Thank you for the great work @delmoralsu and @jaeltan ! I left a few suggestions and comments, please let me know if you have ay questions.

2023-03-16 10:56 UTC, henriquesposito commented on NEWS.md
> +2023-03-15
Could you please add also issue #61 here somewhere? I have added a `create_memberships()`function.

2023-03-16 10:56 UTC, henriquesposito commented on R/manyenviron-agreements.R
> +#' 48 variables: manyID, Title, Beg, End, Signature, Force, url, AgreementType, DocType, GeogArea, gengID, ieaID, ecolexID, treatyID, Parties, verified, DocValidUntilDate, Notes, Download, MEA_type,
Several lines here, and below, are above 80 characters, we should split these. Could you please run `lintr::lint_package()` and adress those issues whenever possible throughout the package?

2023-03-16 10:56 UTC, henriquesposito commented on data-raw/agreements/AIGGO/prepare-AIGGO.R
> +# Remove NAs for manyIDs
How many NA many IDs do we have? @jaeltan Do you know why we are getting these? Maybe there is a bug with `generate_agreements()`? Thank you.

2023-03-16 10:56 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
>      - memberships
Are we removing organizations from the website?

2023-03-17 08:31 UTC, jaeltan commented on data-raw/agreements/AIGGO/prepare-AIGGO.R
> +# Remove NAs for manyIDs
This is an old issue that was carried over from the HUGGO dataset, which I resolved there before Diego started verifying the data. The NAs were caused because the manyIDs had not been generated taking into account the other datasets in the package. I have removed the lines removing the NAs for manyIDs in the script now since it won't be an issue anymore. I can also re-export the AIGGO dataset, but I'm wondering how useful that is, depending on the ways we are re-working the AIGGO dataset with the new treaty texts that we have. @henriquesposito

2023-03-17 10:51 UTC, delmoralsu commented on NEWS.md
> +2023-03-15
Done! Please let me know if the description of the function is fair.

2023-03-20 10:38 UTC, henriquesposito commented on data-raw/agreements/AIGGO/prepare-AIGGO.R
> +# Remove NAs for manyIDs
Thank you @jaeltan ! If this is not an issue anymore here, we can just let it as is here and revisit this once we start to work more on AIGGO.

2023-03-21 08:54 UTC, henriquesposito approved these changes
@jaeltan and @delmoralsu thank you for the great work! Just a few corrections left on my side and then we should be good to go!

2023-03-21 08:54 UTC, henriquesposito commented on R/generate_agreements.R
> +#' @param treaty_type What type of treaty would you likebe returned?
Could you please fix the spelling mistakes and make sure this is more concise and consistent with the below/above function?

2023-03-21 08:54 UTC, henriquesposito commented on tests/testthat/tets_generate.R
> +  expect_length(generate_memberships(12, list = TRUE)[,1], 12)
Could you please rename this file to correct spelling mistake?

2023-03-21 08:54 UTC, henriquesposito commented on pkgdown/_pkgdown.yml
Could we please make sure, before merging, that the vignettes and pkgdown site builds correctly?

2023-03-22 11:03 UTC, merged